version: "3"
services:
  registry:
    image: registry
    container_name: registry 
    ports:
      - 5000:5000      
    volumes:
      - registry:/var/lib/registry
    restart: "unless-stopped"
volumes:
  registry: 
